### ISSUE TITLE
LSP servers not being found by nvim after installation with nvim-lsp-installer

### ISSUE THREAD

**Issue by ragdoll2iguess** [shaunsingh/nyoom.nvim#2]
As above. I installed ltex and texlab (latex lsps) on two separate occasions, and hls (haskell lsp). None of these are found by LspInfo, and none of these are attached to buffers with relevant filetypes.

**Comment by shaunsingh** [comment]
Should be fixed in the latest commit, I just installed sumneko_lua to test and :LspInfo looks correct now. Thanks for the report, lmk if anything else pops up

**Comment by ragdoll2iguess** [comment]
Hmmmm, it's still not behaving correctly on my end after replacing everything with the latest commit.

I added in:
> -- lsp server configs
> require'lspconfig'.texlab.setup{}

And now texlab shows up correctly in :LspInfo, but fails to initialize (executable missing from path error, despite it literally not being missing). I'm genuinely confused why it's not working out, this is a completely fresh install. Considering reinstalling nvim completely.

**Comment by shaunsingh** [comment]
Just ran into issues with pyright again, I'm not sure whats causing it (configuration itself looks fine) but I'll just rewrite the whole lspconfig section. Its long overdue and hopefully it fixes this issue

**Comment by shaunsingh** [comment]
Finally fixed it, properly this time: https://github.com/shaunsingh/nyoom.nvim/commit/98ad880bcad4c76798088f28f7265d0bf8445aef
